# Generated by Django 5.1.1 on 2024-09-29 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(max_length=600)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "expire_time",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2024, 9, 29, 15, 40, 44, 391861),
                        null=True,
                    ),
                ),
            ],
        ),
    ]
