# Generated by Django 5.1.1 on 2024-09-25 14:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(max_length=600)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "expire_time",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(1, 9, 25, 17, 31, 35, 237597),
                        null=True,
                    ),
                ),
                (
                    "asigned_to",
                    models.ManyToManyField(related_name="asigned", to="user.user"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
