# Generated by Django 5.1.1 on 2024-09-25 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="expire_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(1, 9, 25, 17, 57, 3, 968276),
                null=True,
            ),
        ),
    ]
