# Generated by Django 5.1.1 on 2024-09-29 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="expire_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 9, 29, 15, 51, 29, 505581),
                null=True,
            ),
        ),
    ]
