# Generated by Django 5.1.1 on 2024-09-28 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_expire_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="expire_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 9, 28, 13, 0, 45, 866452),
                null=True,
            ),
        ),
    ]
