# Generated by Django 5.1.1 on 2024-09-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
    ]
