# Generated by Django 5.1.1 on 2024-09-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_is_active_user_usertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ImageField(blank=True, upload_to="profile"),
        ),
    ]
